### ISSUE TITLE
「【依頼】最終課題挙動確認」

### ISSUE THREAD

**Issue by YuyaMimura** [AyakoShirono/fleamarket_sample_80g#37]
■ URL
IPアドレス：18.182.57.30/
Github（最終課題のリポジトリ）：https://github.com/AyakoShirono/fleamarket_sample_80g

■ Basic認証
ID：shirono
Pass：chatspace

■ テスト用アカウント
◯ 購入者用
メールアドレス：test@gmail.com
パスワード：1234567

◯ 購入用カード情報
番号：4242424242424242
期限：12/28
セキュリティカード：1234

◯ 出品者用
メールアドレス：sample@gmail.com
パスワード：0000000

**Comment by TECHCAMP555** [comment]
YuyaMimura さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・建物名を入力しないと登録できない（必須項目ではない）
https://gyazo.com/bd15454cde71cafa2eebf7445322366a

[修正推奨箇所]
・出品画像のビューが崩れている
・出品内容・販売価格が適切であるか
※あくまで修正は任意ですが、企業の方が目にされるのでご検討ください。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by AyakoShirono** [comment]
建物名の制限を解除し、出品のビュー修正とバリデーションで価格の範囲指定を行いました。
ご確認をよろしくお願いいたします。

**Comment by rumaruma0408** [comment]
AyakoShironoさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

以下は必須確認項目にはございませんが修正推奨箇所となります。
◯出品時の価格範囲が200円~となっているが200円だと出品できない。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
